# Generated by Django 4.0.6 on 2022-07-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='service',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
