# Generated by Django 4.0.6 on 2022-07-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0004_rename_subject_message_thema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='nachname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='thema',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='message',
            name='vorname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
