# Generated by Django 4.0.6 on 2022-07-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0005_alter_message_email_alter_message_nachname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='dauer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='services',
            name='preis',
            field=models.IntegerField(default=0),
        ),
    ]
