# Generated by Django 4.0.6 on 2022-07-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0006_alter_services_dauer_alter_services_preis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='dauer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='nachname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='nummer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='preis',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='service',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='uhrzeit',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='vorname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='nachname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='thema',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='message',
            name='vorname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='services',
            name='dauer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='preis',
            field=models.IntegerField(),
        ),
    ]
