# Generated by Django 4.0.6 on 2022-07-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0007_alter_bookings_dauer_alter_bookings_nachname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='groupe',
            new_name='gruppe',
        ),
    ]
